title: Bruno Firmino
description: "My Tech Zone"
author:
  name: "Bruno Firmino"
  email: "brunofirmino@protonmail.com"
  url: "https://bfirmino.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Bruno Firmino"
year : "2021"
